controllers/PostController.php
<?php

namespace app\controllers;

use app\models\Category;
use Yii;
use app\models\TestForm;

class PostController extends AppController
{

    public $layout = 'basic';

    public function actionIndex()
    {
        if (Yii::$app->request->isAjax) {
//            $this->debug($_GET);
            Yii::$app->request->post();
            return 'test';
        }

//        $post = TestForm::findOne(1);
//        $post->email = 'test@test.com';
//        $post->save();
//        $post->delete();


        $model = new TestForm();

//        $model->name = 'Имя модели';
//        $model->email = 'email@email.com';
//        $model->text = 'Текст модели';
//        $model->save();


        if ($model->load(Yii::$app->request->post())) {
            if ($model->save()) {
                Yii::$app->session->setFlash('success', 'Данные приняты');
                return $this->refresh();
            } else {
                Yii::$app->session->setFlash('error', 'Ошибка предачи данных');
            }
        }

        return $this->render('index', compact('model'));
    }

    public function actionShow()
    {
        $this->view->title = 'Одна статья';
        $this->view->registerMetaTag(['name' => 'keywords', 'content' => 'ключевые слова']);
        $this->view->registerMetaTag(['name' => 'description', 'content' => 'описание страницы']);

//        $cats = Category::find()->all();
//        $cats = Category::find()->orderBy(['id' => SORT_DESC])->all();  // сотрировка id по убыванию
//        $cats = Category::find()->asArray()->all();  // достаем данные массивом (потребляет меньше памяти, меньше запроосов)
//            $cats ['title'];  // в этом случае так обращаться к данным массива
//        $cats = Category::find()->asArray()->where('parent=691')->all();  // выбираем все данные parent со знач. 691
//        $cats = Category::find()->asArray()->where(['parent' => 691])->all();  // выбираем все данные parent со знач. 691
//        $cats = Category::find()->asArray()->where('parent=691')->limit(1)->all();  // выбираем один parent со знач. 691
//        $cats = Category::find()->asArray()->where('parent=691')->limit(1)->one();  // выбираем один parent со знач. 691, при этом формируется одномерный массив
//        $cats = Category::find()->asArray()->where(['like', 'title', 'pp'])->all();  // выбираем из title все ячейки с буквами "pp"
//        $cats = Category::find()->asArray()->where(['<=', 'id', 695])->all();  // выбираем из id все ячейки до 695 включительно
//        $cats = Category::find()->asArray()->where(['<=', 'id', 695])->count();  // выводит кол-во ячеек с id до 695 включительно
//        $cats = Category::findOne(['parent' => 691]);  // выводит один объект со значением parent = 691
//        $cats = Category::findAll(['parent' => 691]);  // выводит все объекты со значением parent = 691

//        $query = "SELECT * FROM categories WHERE title LIKE '%pp%' ";   // SQL запрос (опасен, возможны SQL инъекции)
//        $cats = Category::findBySql($query)->all();

//        $query = "SELECT * FROM categories WHERE title LIKE :search";   // SQL запрос - безопасен
//        $cats = Category::findBySql($query, [':search' => '%pp%'])->all();

        return $this->render('show', compact('cats'));
    }
}

views/layouts/basic.php
<?php

use app\assets\AppAsset;
use yii\helpers\Html;

AppAsset::register($this);
?>

<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">

<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= $this->title ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>
<div class="wrap">
    <div class="container">
        <ul class="nav nav-pills">
            <li role="presentation" class="active"><?= Html::a('Главная', '/web/');?></li>
            <li role="presentation"><?= Html::a('Статьи', ['post/index']);?></li>
            <li role="presentation"><?= Html::a('Статья', ['post/show']);?></li>
        </ul>

        <?php if (isset($this->blocks['block1'])): ?>
            <?php echo $this->blocks['block1'] ?>
        <?php endif; ?>

        <?= $content ?>
    </div>
</div>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'my Company',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Home', 'url' => ['/site/index']],
            ['label' => 'About', 'url' => ['/site/about']],
            ['label' => 'Contact', 'url' => ['/site/contact']],
            Yii::$app->user->isGuest ? (
                ['label' => 'Login', 'url' => ['/site/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post')
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>